apiVersion: v1
kind: Service
metadata:
  name: beanstalkd
  labels:
    app: beanstalkd
spec:
  ports:
    - port: 11300
  selector:
    app: beanstalkd
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: beanstalkd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beanstalkd
    spec:
      containers:
      - name: beanstalkd
        image: "jonbaldie/beanstalkd:latest"
        ports:
            - containerPort: 11300
