apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: workers-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: workers-controller
    spec:
      containers:
      - name: workers-controller
        image: "beanstalkd-workers-controller:1.0"
